name: Lint and Test on PRs

on:
  pull_request:
    branches: ["main"]

env:
  GO_VERSION: '1.24'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: src/go.sum

      - name: Run linting checks
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: src/go.sum

      - name: Build binary
        run: make build

      - name: Run unit tests
        run: make test-unit

      - name: Generate test coverage report
        run: make test-coverage

      - name: Run integration tests
        run: make test-integration
